name: Test on pull request
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
    runs-on: ubuntu-18.04
    env:
      DETA_SDK_TEST_BASE_NAME: ${{secrets.DETA_SDK_TEST_BASE_NAME}}
      DETA_SDK_TEST_PROJECT_KEY: ${{secrets.DETA_SDK_TEST_PROJECT_KEY}}
      DETA_SDK_TEST_ENDPOINT: ${{secrets.DETA_SDK_TEST_ENDPOINT}}
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Test
      - name: Test code
        run: go test