name: Lint on pull request
on:
  pull_request:
    branches:
      - master

jobs:
  full_ci:
    strategy:
      matrix:
        go-version: [1.14.x]
    runs-on: ubuntu-18.04
    steps:
      # Get the code into the container
      - name: Checkout
        uses: actions/checkout@v2
      # Test the code
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
      - name: Test code
        run: go test -json ./... > test.json
      - name: Print results
        run: cat test.json
      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annoations@v0.3.0
        with:
          test-results: test.json
      